trigger:
  branches:
    include:
    - master
  paths:
    include:
    - SportPlannerApi

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build

  jobs:
  - job: Build
    variables:
      configuration: release

    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Publish'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--output $(Build.ArtifactStagingDirectory) -c $(configuration)'
        zipAfterPublish: True
      
    - publish: $(Build.ArtifactStagingDirectory)/SportPlannerApi.zip
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'development'

    strategy:
      runOnce:
        deploy:

          steps:
          - task: AzureRmWebAppDeployment@4
            displayName: 'Web app deploy'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Azure-prenumeration-mattiaslij(96ba612d-6300-44c9-98f2-494e13d2d962)'
              appType: 'webAppLinux'
              WebAppName: 'sp-wa-api'
              packageForLinux: '$(Pipeline.Workspace)/drop/SportPlannerApi.zip'
